version: "3"
services:
  client:
    restart: always
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    restart: always
    build: ./api
    ports:
      - "4000:4000"
    volumes:
    - ./api:/api

