version: "3"
services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
